_BASE_: "Base-RCNN-FPN-xView3.yaml"
MODEL:
  MASK_ON: False
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x/139173657/model_final_68b088.pkl"
  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
DATASETS:
  TRAIN: ("xview3-full-train",)
  TEST: ("xview3-full-valid",)
DATALOADER:
  SAMPLER_TRAIN: TrainingSampler
  DATASET_TRAIN: xView3FullSceneDataset 
INPUT:
  AUG:
    - {name: MinMaxNormalize, per_channel: True}
    - {name: RandomFlip, prob: 0.5, horizontal: False, vertical: True}
    - {name: RandomFlip, prob: 0.5, horizontal: True, vertical: False}  
TEST:
  INPUT:
    AUG:
      - {name: MinMaxNormalize, per_channel: True}

