from detectron2.config import CfgNode as CN


def add_xview3_config(cfg):
    _C = cfg
    # Experiment name is autogenerated from config name and timestamp.
    _C.EXP_NAME = ''
    
    _C.DATALOADER.FILTER_EMPTY_ANNOTATIONS = False
    _C.DATALOADER.DATASET_TRAIN = "xView3FullSceneDataset"
    _C.DATALOADER.NUM_WORKERS = 0

    # Inputs to xView3Dataset
    _C.INPUT.DATA = CN()
    _C.INPUT.DATA.CHIP_SIZE = 1280
    _C.INPUT.DATA.CHIP_MAX_JITTER = 128
    _C.INPUT.DATA.CHANNEL_NAMES = ["VH_dB", "VV_dB", "bathymetry"]
    _C.INPUT.DATA.SHORELINE_DIR = None
    _C.INPUT.DATA.CLOSE_TO_SHORE_KM = 2
    _C.INPUT.DATA.PROP_DETECTIONS = 0.8
    _C.INPUT.DATA.BALANCE_NEAR_SHORE = True
    _C.INPUT.DATA.BALANCE_CROWDED = True
    _C.INPUT.DATA.BALANCE_CATEGORIES = True
    _C.INPUT.DATA.CHIP_OVERLAP = 32
    _C.INPUT.DATA.CV2_RESIZE = True
    _C.INPUT.DATA.PROP_NODATA_PIXELS = 0.8
    _C.INPUT.DATA.FILL_NODATA_VAL = "mean"
    _C.INPUT.DATA.FILL_NODATA_GLOBAL = True
    _C.INPUT.DATA.LENGTHS_FILL_NAN = "mean"

    # Vessel length stats in meters.
    # Values below were computed by bootstrapping (n=1000) the vessel
    # lengths in the combined train-val set and taking the average.
    _C.INPUT.DATA.TRAIN_LENGTH_STATS = '{"min": 6.27, "median": 41.58, "mean": 64.28}'

    _C.INPUT.AUG = []

    _C.TEST.INPUT = CN()
    _C.TEST.INPUT.CHIP_SIZE = _C.INPUT.DATA.CHIP_SIZE
    _C.TEST.INPUT.SHORELINE_DIR = None
    _C.TEST.INPUT.CLOSE_TO_SHORE_KM = _C.INPUT.DATA.CLOSE_TO_SHORE_KM
    _C.TEST.INPUT.CHIP_OVERLAP = _C.INPUT.DATA.CHIP_OVERLAP
    _C.TEST.INPUT.AUG = []
    _C.TEST.IMS_PER_BATCH = 1
    _C.TEST.IOU_THRESHOLD = 0.1
    _C.TEST.SCORE_THRESHOLD = 0.0
    _C.TEST.SCORE_ALL = False

    # For full scene, format of data.
    _C.INPUT.SCENE_FORMAT = "hdf5"
    _C.TEST.INPUT.SCENE_FORMAT = _C.INPUT.SCENE_FORMAT

    _C.SOLVER.RESET_ITER = True
    _C.SOLVER.TRAIN_ITER = -1
    _C.SOLVER.AMP.ENABLED = True

    _C.DEBUG = False
    _C.SAVE_DEBUG = False

    _C.MODEL.ROI_BOX_HEAD.LENGTH_REG_LOSS_WEIGHT = 0.1
    _C.MODEL.ROI_BOX_HEAD.LENGTH_REG_LOSS_TYPE = (
        "smooth_l1"  # options ['mse', 'smooth_l1', 'bce']
    )
    _C.MODEL.ROI_BOX_HEAD.LENGTH_REG_ORDINAL = False  # Use ordinal regression.
    _C.MODEL.ROI_BOX_HEAD.LENGTH_MAX = 500  # Maximum length of vessels.
    _C.MODEL.ROI_BOX_HEAD.CLS_AGNOSTIC_LENGTH_REG = False
    _C.MODEL.ROI_BOX_HEAD.USE_FED_LOSS = False
    _C.MODEL.ROI_BOX_HEAD.USE_SIGMOID_CE = False
    _C.MODEL.ROI_BOX_HEAD.FED_LOSS_FREQ_WEIGHT_POWER = 1
    _C.MODEL.ROI_BOX_HEAD.FED_LOSS_NUM_CLASSES = 3
